import fs from 'node:fs';
import path from 'node:path';

import { MiscUtils } from '@callstack/licenses';

const ANDROID_PLUGIN_APPLY_BLOCK_IDENTIFIER = 'com.mikepenz.aboutlibraries.plugin.android';
const ANDROID_PLUGIN_APPLY_BLOCK = `apply plugin: "${ANDROID_PLUGIN_APPLY_BLOCK_IDENTIFIER}"`;
const ANDROID_PLUGIN_CLASSPATH =
  'com.mikepenz.aboutlibraries.plugin.android:com.mikepenz.aboutlibraries.plugin.android.gradle.plugin';
const ANDROID_PLUGIN_DEFAULT_VERSION = '13.1.0';
const GRADLE_PLUGIN_PORTAL = 'gradlePluginPortal()';
const PLUGIN_APPLY_BLOCK_IDENTIFIER = 'com.mikepenz.aboutlibraries.plugin';

const OLD_PLUGIN_CLASSPATH = 'com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin';
const OLD_PLUGIN_CLASSPATH_REGEX = new RegExp(
  `\\s+classpath\\(['"]${OLD_PLUGIN_CLASSPATH}:\\d+\\.\\d+\\.\\d+['"]\\)\\n`,
);
const DEPENDENCIES_BLOCK_DECLARATION_REGEX = new RegExp('dependencies\\s*{');
const REPOSITORIES_BLOCK_DECLARATION_REGEX = new RegExp('repositories\\s*{');
const APPLY_PLUGIN_BLOCK_REGEX = new RegExp(`apply\\s+plugin:\\s+['"]${PLUGIN_APPLY_BLOCK_IDENTIFIER}['"]\\n`);
const APPLY_ANDROID_PLUGIN_BLOCK_REGEX = new RegExp(
  `apply\\s+plugin:\\s+['"]${ANDROID_PLUGIN_APPLY_BLOCK_IDENTIFIER}['"]`,
);
const OLD_PLUGIN_CONFIG_BLOCK_REGEX = new RegExp('(?:\\s*aboutLibraries\\s*{\\s+)(?:(?:\\S+\\s*=\\s*\\S+\\s+)*)(?:})');
const NEW_PLUGIN_CONFIG_GENERATED_START_COMMENT = '// GENERATED BY REACT-NATIVE-LEGAL DO NOT EDIT!\n';
const NEW_PLUGIN_CONFIG_GENERATED_END_COMMENT = '// END OF GENERATED BY REACT-NATIVE-LEGAL\n';
const NEW_PLUGIN_CONFIG_REGEX = new RegExp(
  '(?:\\/\\/ GENERATED BY REACT-NATIVE-LEGAL DO NOT EDIT!\\n)(?:[\\s\\S]+)(?:\\/\\/ END OF GENERATED BY REACT-NATIVE-LEGAL\\n)',
);

/**
 * Applies Gradle Plugin Portal & AboutLibraries Gradle plugin repositories (if needed) inside root build.gradle
 */
export function declareAboutLibrariesPluginUtil(androidBuildGradleContent: string) {
  if (androidBuildGradleContent.match(OLD_PLUGIN_CLASSPATH)?.length) {
    // Remove old plugin
    androidBuildGradleContent = androidBuildGradleContent.replace(OLD_PLUGIN_CLASSPATH_REGEX, '');
  }

  if (!androidBuildGradleContent.match(ANDROID_PLUGIN_CLASSPATH)?.length) {
    // Declare the AboutLibraries plugin
    androidBuildGradleContent = androidBuildGradleContent.replace(
      DEPENDENCIES_BLOCK_DECLARATION_REGEX,
      `dependencies {\n        classpath("${ANDROID_PLUGIN_CLASSPATH}:${ANDROID_PLUGIN_DEFAULT_VERSION}")`,
    );
    console.log('About Libraries Gradle Plugin repository - ADDED');
  } else {
    console.log('About Libraries Gradle Plugin already added - SKIP');
  }

  if (androidBuildGradleContent.match(GRADLE_PLUGIN_PORTAL_URL)?.length) {
    console.log('Gradle Plugin Portal repository already added - SKIP');
  } else if (!androidBuildGradleContent.match(GRADLE_PLUGIN_PORTAL)?.length) {
    // Add Gradle Plugin Portal repository if it's not included
    androidBuildGradleContent = androidBuildGradleContent.replace(
      REPOSITORIES_BLOCK_DECLARATION_REGEX,
      'repositories {\n        gradlePluginPortal()',
    );
    console.log('Gradle Plugin Portal repository - ADDED');
  }

  return androidBuildGradleContent;
}

/**
 * Applies and configures AboutLibraries Grale plugin (if needed) inside app's build.gradle
 */
export function applyAndConfigureAboutLibrariesPluginUtil(androidAppBuildGradleContent: string) {
  if (androidAppBuildGradleContent.match(APPLY_PLUGIN_BLOCK_REGEX)?.length) {
    // Remove old plugin
    androidAppBuildGradleContent = androidAppBuildGradleContent.replace(APPLY_PLUGIN_BLOCK_REGEX, '');
  }

  // Remove old configuration
  androidAppBuildGradleContent = androidAppBuildGradleContent.replace(OLD_PLUGIN_CONFIG_BLOCK_REGEX, '');

  if (!androidAppBuildGradleContent.match(APPLY_ANDROID_PLUGIN_BLOCK_REGEX)?.length) {
    // Apply plugin
    androidAppBuildGradleContent += `\n${ANDROID_PLUGIN_APPLY_BLOCK}\n`;
    console.log('About Libraries Gradle Plugin - APPLIED');
  } else {
    console.log('About Libraries Gradle Plugin already applied - SKIP');
  }

  let aboutLibrariesConfig = '\n';

  aboutLibrariesConfig += NEW_PLUGIN_CONFIG_GENERATED_START_COMMENT;
  aboutLibrariesConfig += 'aboutLibraries {\n';
  aboutLibrariesConfig += '  offlineMode = false\n';
  aboutLibrariesConfig += '  collect.configPath = file("../config")\n';
  aboutLibrariesConfig += '  collect.fetchRemoteLicense = false\n';
  aboutLibrariesConfig += '  collect.fetchRemoteFunding = false\n';
  aboutLibrariesConfig += '  export {\n';
  aboutLibrariesConfig += '    prettyPrint = true\n';
  aboutLibrariesConfig += '  }\n';
  aboutLibrariesConfig += '}\n';
  aboutLibrariesConfig += NEW_PLUGIN_CONFIG_GENERATED_END_COMMENT;

  // Configure plugin
  if (androidAppBuildGradleContent.match(NEW_PLUGIN_CONFIG_REGEX)?.length) {
    androidAppBuildGradleContent = androidAppBuildGradleContent.replace(NEW_PLUGIN_CONFIG_REGEX, aboutLibrariesConfig);
  } else {
    androidAppBuildGradleContent += aboutLibrariesConfig;
  }

  console.log('About Libraries Gradle Plugin - CONFIGURED');

  return androidAppBuildGradleContent;
}

/**
 * adds a list activity to the list of application's activities
 */
export function addListActivityUtil<T>(activities: T[]): T[] {
  const listActivity = prepareListActivity();

  if (!MiscUtils.arrayIncludesObject(activities, listActivity)) {
    activities?.push(listActivity as T);
    console.log('About Libraries activity - ADDED');
  } else {
    console.log('About Libraries activity already added - SKIP');
  }

  return activities;
}

/**
 * This JS object will evaluate to the following XML content:
 *
 * <activity
 *   android:name="com.reactnativelegal.ReactNativeLegalActivity"
 *   android:exported="false"
 *   android:launchMode="singleTask"
 * />
 */
function prepareListActivity() {
  return {
    $: {
      'android:name': PLUGIN_ACTIVITY,
      'android:exported': 'false',
      'android:launchMode': 'singleTask',
    },
  } as const;
}

const RESOURCE_KEEP_FILE_CONTENT = `<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@raw/aboutlibraries" />
`;

/**
 * adds a file that will keep the About Libraries json resource when resource shrinking is enabled
 */
export function addResourceKeepFileUtil(androidProjectRootDir: string) {
  const rawResourcesDir = path.join(androidProjectRootDir, 'app/src/main/res/raw');
  const keepFilePath = path.join(rawResourcesDir, 'com_reactnativelegal_keep.xml');

  if (!fs.existsSync(rawResourcesDir)) {
    fs.mkdirSync(rawResourcesDir, { recursive: true });
  }

  if (!fs.existsSync(keepFilePath)) {
    fs.writeFileSync(keepFilePath, RESOURCE_KEEP_FILE_CONTENT);
    console.log('Android resource keep file - ADDED');
  } else {
    console.log('Android resource keep file already exists - SKIPPED');
  }
}

const GRADLE_PLUGIN_PORTAL_URL = 'https://plugins.gradle.org/m2';
const PLUGIN_ACTIVITY = 'com.reactnativelegal.ReactNativeLegalActivity';
