name: Bare Example E2E Tests

on:
  push:
    branches: [main]
    paths:
      - 'packages/react-native-legal/**'
      - 'examples/bare-example/**'
      - '.github/workflows/bare-example-e2e.yml'
  pull_request:
    paths:
      - 'packages/react-native-legal/**'
      - 'examples/bare-example/**'
      - '.github/workflows/bare-example-e2e.yml'

jobs:
  android-e2e:
    name: Android E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/bare-example
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Generate legal notices
        run: yarn react-native legal-generate
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Build and install Android
        id: build-android
        uses: callstackincubator/android@v1
        with:
          variant: 'release'
          working-directory: examples/bare-example

      - name: Install Android app
        run: |
          adb install -r "${{ steps.build-android.outputs.artifact-url }}" || {
            echo "Error: Failed to install Android APK"
            exit 1
          }
          
      - name: Run Android E2E tests
        run: yarn e2e:android
        
  ios-e2e:
    name: iOS E2E Tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: examples/bare-example
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Generate legal notices
        run: yarn react-native legal-generate
        
      - name: Build iOS
        id: build-ios
        uses: callstackincubator/ios@v1
        with:
          destination: 'simulator'
          scheme: 'ReactNativeLegalBareExample'
          configuration: 'Release'
          working-directory: examples/bare-example
          
      - name: Setup iOS Simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 15'
          
      - name: Install and launch app
        run: |
          xcrun simctl install booted "${{ steps.build-ios.outputs.artifact-url }}" || {
            echo "Error: Failed to install iOS app"
            exit 1
          }
          
      - name: Run iOS E2E tests
        run: yarn e2e:ios