name: Expo Example - Android E2E Tests
on:
  push:
    branches: [ main ]
    paths:
      - 'examples/expo-example/**'
      - 'packages/**'
      - '.github/workflows/e2e-expo-example-android.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/expo-example/**'
      - 'packages/**'
      - '.github/workflows/e2e-expo-example-android.yml'
  workflow_dispatch:

jobs:
  android-e2e:
    name: Run Expo Example Android E2E Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/expo-example
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/actions/setup
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Build and run Android app
        run: CI=1 yarn expo run:android
      
      - name: Run Maestro tests
        run: maestro test ./e2e/android-flow.yaml