name: Expo Example - iOS E2E Tests
on:
  push:
    branches: [ main ]
    paths:
      - 'examples/expo-example/**'
      - 'packages/**'
      - '.github/workflows/e2e-expo-example-ios.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/expo-example/**'
      - 'packages/**'
      - '.github/workflows/e2e-expo-example-ios.yml'
  workflow_dispatch:

jobs:
  ios-e2e:
    name: Run Expo Example iOS E2E Tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: examples/expo-example
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
      
      - name: Build and run iOS app
        run: CI=1 yarn expo run:ios
      
      - name: Run Maestro tests
        run: maestro test ./e2e/ios-flow.yaml