name: Unit tests - React Native Legal Shared package

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-unit-shared.yml'
      - 'packages/shared/**/*.[tj]sx?'

  push:
    branches:
      - main

  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unit-test-shared:
    name: Run unit tests for @callstack/licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn workspace @callstack/licenses test
