name: E2E tests - iOS

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-e2e-ios.yaml'
      - 'examples/bare-example/e2e/checkLicenses/ios.yaml'
      - 'examples/bare-example/e2e/checkLicenses/ios-get-licenses.yaml'
      - 'packages/react-native-legal/**/*.[tj]sx?'
      - 'packages/react-native-legal/ios/**'
      - 'packages/licenses-api/**/*.[tj]sx?'
      - 'examples/bare-example/**/*.[tj]sx?'
      - 'examples/bare-example/ios/**'

  push:
    branches:
      - main

  workflow_dispatch:

env:
  MAESTRO_CLI_NO_ANALYTICS: true
  MAESTRO_CLI_ANALYSIS_NOTIFICATION_DISABLED: true
  MAESTRO_DISABLE_UPDATE_CHECK: true

concurrency:
  group: e2e_tests-ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-ios:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        simulator: ['iPhone 16 Pro']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install Maestro
        uses: ./.github/actions/installMaestro
        with:
          target-platform: ios

      - name: Install example dependencies
        run: yarn workspace react-native-legal-bare-example install --immutable

      - name: Cache Pods
        id: cache-pods
        uses: actions/cache@v4
        env:
          cache-name: cached-ios-pods
        with:
          path: examples/bare-example/ios/Pods
          key: bare-example-pods-${{ matrix.simulator }}-${{ hashFiles('ios/Podfile.lock') }}

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v4
        env:
          cache-name: cached-ios-build
        with:
          path: examples/bare-example/ios/build
          key: bare-example-ios-build-${{ matrix.simulator }}

      - name: Install gems
        run: yarn workspace react-native-legal-bare-example gem:install

      - name: Install example Pods
        run: yarn workspace react-native-legal-bare-example pod:install

      - name: Bundle app
        run: yarn workspace react-native-legal-bare-example build:ios

      - name: List simulators
        run: xcrun simctl list

      - name: Build iOS App
        run: yarn workspace react-native-legal-bare-example ios:release --simulator="${{ matrix.simulator }}"

      - name: Run tests
        run: yarn workspace react-native-legal-bare-example e2e:ios

      - name: Upload report
        if: always()
        continue-on-error: true
        uses: ./.github/actions/uploadMaestroTestResults
        with:
          id: ${{ matrix.simulator }}
